version: "3.9"
services:

  ccrso:
    build: ./
    container_name: ccrso
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/weather
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CITIESLIST_PATH: /app/cities.txt
      OPENWEATHERMAP_APPID: ${APPID}
    volumes:
      - ${CITIESLIST_PATH}:/app/cities.txt
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
    volumes:
    - ${DB_DATA_PATH}:/var/lib/postgresql
    networks:
      - default

networks:
  default: null